#!/bin/bash
cat /usr/share/doc/libpam-runtime/copyright       > libpam-runtime.txt        
cat /usr/share/doc/libpam0g/copyright             > libpam0g.txt              
cat /usr/share/doc/base-passwd/copyright          > base-passwd.txt           
cat /usr/share/doc/lsb-base/copyright             > lsb-base.txt              
cat /usr/share/doc/libnsl2/copyright              > libnsl2.txt               
cat /usr/share/doc/libp11-kit0/copyright          > libp11-kit0.txt           
cat /usr/share/doc/diffutils/copyright            > diffutils.txt             
cat /usr/share/doc/findutils/copyright            > findutils.txt             
cat /usr/share/doc/init-system-helpers/copyright  > init-system-helpers.txt   
cat /usr/share/doc/libblkid1/copyright            > libblkid1.txt             
cat /usr/share/doc/libtinfo6/copyright            > libtinfo6.txt             
cat /usr/share/doc/libgmp10/copyright             > libgmp10.txt              
cat /usr/share/doc/sed/copyright                  > sed.txt                   
cat /usr/share/doc/libselinux1/copyright          > libselinux1.txt           
cat /usr/share/doc/dash/copyright                 > dash.txt                  
cat /usr/share/doc/libacl1/copyright              > libacl1.txt               
cat /usr/share/doc/gzip/copyright                 > gzip.txt                  
cat /usr/share/doc/libpcre3/copyright             > libpcre3.txt              
cat /usr/share/doc/libpam-modules/copyright       > libpam-modules.txt        
cat /usr/share/doc/logsave/copyright              > logsave.txt               
cat /usr/share/doc/debianutils/copyright          > debianutils.txt           
cat /usr/share/doc/debconf/copyright              > debconf.txt               
cat /usr/share/doc/libattr1/copyright             > libattr1.txt              
cat /usr/share/doc/base-files/copyright           > base-files.txt            
cat /usr/share/doc/libpcre2-8-0/copyright         > libpcre2-8-0.txt          
cat /usr/share/doc/libpam-modules-bin/copyright   > libpam-modules-bin.txt    
cat /usr/share/doc/libcom-err2/copyright          > libcom-err2.txt           
cat /usr/share/doc/bash/copyright                 > bash.txt                  
cat /usr/share/doc/libtirpc-common/copyright      > libtirpc-common.txt       
cat /usr/share/doc/libkrb5-3/copyright            > libkrb5-3.txt             
cat /usr/share/doc/libss2/copyright               > libss2.txt                
cat /usr/share/doc/libtirpc3/copyright            > libtirpc3.txt             
cat /usr/share/doc/libaudit1/copyright            > libaudit1.txt             
cat /usr/share/doc/libkrb5support0/copyright      > libkrb5support0.txt       
cat /usr/share/doc/hostname/copyright             > hostname.txt              
cat /usr/share/doc/gpgv/copyright                 > gpgv.txt                  
cat /usr/share/doc/libdebconfclient0/copyright    > libdebconfclient0.txt     
cat /usr/share/doc/adduser/copyright              > adduser.txt               
cat /usr/share/doc/debian-archive-keyring/copyright >  debian-archive-keyring.txtt
cat /usr/share/doc/libcrypt1/copyright            > libcrypt1.txt             
cat /usr/share/doc/libmount1/copyright            > libmount1.txt             
cat /usr/share/doc/libuuid1/copyright             > libuuid1.txt              
cat /usr/share/doc/libsystemd0/copyright          > libsystemd0.txt           
cat /usr/share/doc/libapt-pkg6.0/copyright        > libapt-pkg6.0.txt         
cat /usr/share/doc/zlib1g/copyright               > zlib1g.txt                
cat /usr/share/doc/libsemanage1/copyright         > libsemanage1.txt          
cat /usr/share/doc/libzstd1/copyright             > libzstd1.txt              
cat /usr/share/doc/mawk/copyright                 > mawk.txt                  
cat /usr/share/doc/libdb5.3/copyright             > libdb5.3.txt              
cat /usr/share/doc/libtasn1-6/copyright           > libtasn1-6.txt            
cat /usr/share/doc/perl-base/copyright            > perl-base.txt             
cat /usr/share/doc/libseccomp2/copyright          > libseccomp2.txt           
cat /usr/share/doc/libidn2-0/copyright            > libidn2-0.txt             
cat /usr/share/doc/libnettle8/copyright           > libnettle8.txt            
cat /usr/share/doc/libc-bin/copyright             > libc-bin.txt              
cat /usr/share/doc/tar/copyright                  > tar.txt                   
cat /usr/share/doc/gcc-10-base/copyright          > gcc-10-base.txt           
cat /usr/share/doc/libsepol1/copyright            > libsepol1.txt             
cat /usr/share/doc/libext2fs2/copyright           > libext2fs2.txt            
cat /usr/share/doc/ncurses-bin/copyright          > ncurses-bin.txt           
cat /usr/share/doc/tzdata/copyright               > tzdata.txt                
cat /usr/share/doc/e2fsprogs/copyright            > e2fsprogs.txt             
cat /usr/share/doc/passwd/copyright               > passwd.txt                
cat /usr/share/doc/grep/copyright                 > grep.txt                  
cat /usr/share/doc/libssl1.1/copyright            > libssl1.1.txt             
cat /usr/share/doc/ncurses-base/copyright         > ncurses-base.txt          
cat /usr/share/doc/liblzma5/copyright             > liblzma5.txt              
cat /usr/share/doc/libsemanage-common/copyright   > libsemanage-common.txt    
cat /usr/share/doc/libgcrypt20/copyright          > libgcrypt20.txt           
cat /usr/share/doc/libgssapi-krb5-2/copyright     > libgssapi-krb5-2.txt      
cat /usr/share/doc/libaudit-common/copyright      > libaudit-common.txt       
cat /usr/share/doc/libxxhash0/copyright           > libxxhash0.txt            
cat /usr/share/doc/util-linux/copyright           > util-linux.txt            
cat /usr/share/doc/libk5crypto3/copyright         > libk5crypto3.txt          
cat /usr/share/doc/mount/copyright                > mount.txt                 
cat /usr/share/doc/coreutils/copyright            > coreutils.txt             
cat /usr/share/doc/dpkg/copyright                 > dpkg.txt                  
cat /usr/share/doc/libsmartcols1/copyright        > libsmartcols1.txt         
cat /usr/share/doc/libudev1/copyright             > libudev1.txt              
cat /usr/share/doc/liblz4-1/copyright             > liblz4-1.txt              
cat /usr/share/doc/login/copyright                > login.txt                 
cat /usr/share/doc/gcc-9-base/copyright           > gcc-9-base.txt            
cat /usr/share/doc/apt/copyright                  > apt.txt                   
cat /usr/share/doc/libgnutls30/copyright          > libgnutls30.txt           
cat /usr/share/doc/libunistring2/copyright        > libunistring2.txt         
cat /usr/share/doc/libbz2-1.0/copyright           > libbz2-1.0.txt            
cat /usr/share/doc/libc6/copyright                > libc6.txt                 
cat /usr/share/doc/libgpg-error0/copyright        > libgpg-error0.txt         
cat /usr/share/doc/libcap-ng0/copyright           > libcap-ng0.txt            
cat /usr/share/doc/libhogweed6/copyright          > libhogweed6.txt           
cat /usr/share/doc/sysvinit-utils/copyright       > sysvinit-utils.txt        
cat /usr/share/doc/bsdutils/copyright             > bsdutils.txt              
cat /usr/share/doc/libffi7/copyright              > libffi7.txt               
cat /usr/share/doc/libkeyutils1/copyright         > libkeyutils1.txt
